### ISSUE TITLE
Modal only has a cancel button

### ISSUE THREAD

**Issue by mattmcmanus** [phibr0/obsidian-macros#4]
Hey! I recently installed the plugin, but I'm not able to create any macros. The modal only has a cancel button and I can't add anything that I add. I've tried deleting the plugin, disabling, restarting Obsidian, etc. 

Here is a screen cap: 

https://user-images.githubusercontent.com/9383/129920068-1efa3d7f-784a-4634-bedf-c50acd4e6579.mp4

**Comment by phibr0** [comment]
The Button to Save your Macro will appear when you have more than one Command added. It wouldn't make much Sense otherwise

**Comment by mattmcmanus** [comment]
I could have sworn I've added multiple and didnt see the button. But alas. There it is. 

![](http://bukk.it/facepalm.jpg)
